---
title: assertThat().contains() 테스트 실패 해결
date: 2022-11-20
tags:
  - error
---

### 에러 상황
assertThat을 활용해 출력문을 테스트하는 코드를 작성하는 와중에 contains로 String 안에 `숫자를 입력해주세요 : `라는 입력값이 있는지 작성했다.  
String 안에 존재했지만 자꾸 테스트가 실패하는 일이 일어났다.

### 테스트 실패
<img width="1281" alt="스크린샷 2022-11-06 오후 3 25 52" src="https://user-images.githubusercontent.com/55697125/200157416-b8680c50-52a8-46ba-8523-cd6bb9f4dcbb.png">

### 해결
NsTest 내부 메서드 output이 `trim()`으로 앞뒤 공백을 제거해줌으로써 출력문에서 `숫자를 입력해주세요 : `뒤에 공백이 제거된 상태로 값이 넘어와서 그랬다.  
메서드에 대한 이해를 더하고 활용 해야겠다고 생각했다...